student(102,'Petrov').
student(101,'Petrovsky').
student(104,'Ivanov').
student(102,'Ivanovsky').
student(104,'Zaporozhcev').
student(101,'Sidorov').
student(103,'Sidorkin').
student(102,'Bitkoinov').
student(103,'Efirkina').
student(103,'Siplusplusov').
student(103,'Programmiro').
student(104,'Javo').
student(103,'Klaviaturnikova').
student(101,'Myshin').
student(104,'Full').
student(101,'Bezumnikov').
student(102,'Sharpin').
student(104,'Krugloschitalkin').
student(103,'Reshetnikov').
student(102,'Excel').
student(102,'Tekstopisov').
student(103,'Tekstopisova').
student(101,'Gustobukvennikova').
student(102,'Kriptovalutnikov').
student(104,'Blockchainis').
student(102,'Azurin').
student(103,'Webservisov').
student(102,'Kruglotlichnikov').

subject('LP','Logical Programming').
subject('MTH','Mathematical Analysis').
subject('FP','Functional Programming').
subject('INF','Informatics').
subject('ENG','English Language').
subject('PSY','Psychology').

grade('Petrov','LP',4).
grade('Petrov','MTH',3).
grade('Petrov','FP',5).
grade('Petrov','INF',4).
grade('Petrov','ENG',4).
grade('Petrov','PSY',3).
grade('Petrovsky','LP',5).
grade('Petrovsky','MTH',5).
grade('Petrovsky','FP',5).
grade('Petrovsky','INF',4).
grade('Petrovsky','ENG',5).
grade('Petrovsky','PSY',3).
grade('Ivanov','LP',5).
grade('Ivanov','MTH',3).
grade('Ivanov','FP',4).
grade('Ivanov','INF',5).
grade('Ivanov','ENG',5).
grade('Ivanov','PSY',5).
grade('Ivanovsky','LP',3).
grade('Ivanovsky','MTH',5).
grade('Ivanovsky','FP',4).
grade('Ivanovsky','INF',3).
grade('Ivanovsky','ENG',5).
grade('Ivanovsky','PSY',5).
grade('Zaporozhcev','LP',2).
grade('Zaporozhcev','MTH',2).
grade('Zaporozhcev','FP',4).
grade('Zaporozhcev','INF',3).
grade('Zaporozhcev','ENG',4).
grade('Zaporozhcev','PSY',4).
grade('Sidorov','LP',4).
grade('Sidorov','MTH',4).
grade('Sidorov','FP',4).
grade('Sidorov','INF',4).
grade('Sidorov','ENG',3).
grade('Sidorov','PSY',4).
grade('Sidorkin','LP',4).
grade('Sidorkin','MTH',5).
grade('Sidorkin','FP',4).
grade('Sidorkin','INF',3).
grade('Sidorkin','ENG',4).
grade('Sidorkin','PSY',4).
grade('Bitkoinov','LP',5).
grade('Bitkoinov','MTH',4).
grade('Bitkoinov','FP',3).
grade('Bitkoinov','INF',4).
grade('Bitkoinov','ENG',3).
grade('Bitkoinov','PSY',2).
grade('Efirkina','LP',2).
grade('Efirkina','MTH',4).
grade('Efirkina','FP',3).
grade('Efirkina','INF',2).
grade('Efirkina','ENG',2).
grade('Efirkina','PSY',4).
grade('Siplusplusov','LP',4).
grade('Siplusplusov','MTH',4).
grade('Siplusplusov','FP',4).
grade('Siplusplusov','INF',5).
grade('Siplusplusov','ENG',4).
grade('Siplusplusov','PSY',4).
grade('Programmiro','LP',5).
grade('Programmiro','MTH',4).
grade('Programmiro','FP',3).
grade('Programmiro','INF',3).
grade('Programmiro','ENG',5).
grade('Programmiro','PSY',4).
grade('Javo','LP',4).
grade('Javo','MTH',4).
grade('Javo','FP',3).
grade('Javo','INF',2).
grade('Javo','ENG',3).
grade('Javo','PSY',5).
grade('Klaviaturnikova','LP',4).
grade('Klaviaturnikova','MTH',5).
grade('Klaviaturnikova','FP',3).
grade('Klaviaturnikova','INF',5).
grade('Klaviaturnikova','ENG',4).
grade('Klaviaturnikova','PSY',4).
grade('Myshin','LP',5).
grade('Myshin','MTH',4).
grade('Myshin','FP',5).
grade('Myshin','INF',4).
grade('Myshin','ENG',3).
grade('Myshin','PSY',3).
grade('Full','LP',4).
grade('Full','MTH',4).
grade('Full','FP',4).
grade('Full','INF',5).
grade('Full','ENG',5).
grade('Full','PSY',5).
grade('Bezumnikov','LP',3).
grade('Bezumnikov','MTH',5).
grade('Bezumnikov','FP',3).
grade('Bezumnikov','INF',2).
grade('Bezumnikov','ENG',4).
grade('Bezumnikov','PSY',3).
grade('Sharpin','LP',3).
grade('Sharpin','MTH',4).
grade('Sharpin','FP',4).
grade('Sharpin','INF',5).
grade('Sharpin','ENG',5).
grade('Sharpin','PSY',5).
grade('Krugloschitalkin','LP',5).
grade('Krugloschitalkin','MTH',2).
grade('Krugloschitalkin','FP',4).
grade('Krugloschitalkin','INF',3).
grade('Krugloschitalkin','ENG',4).
grade('Krugloschitalkin','PSY',3).
grade('Reshetnikov','LP',4).
grade('Reshetnikov','MTH',4).
grade('Reshetnikov','FP',5).
grade('Reshetnikov','INF',3).
grade('Reshetnikov','ENG',5).
grade('Reshetnikov','PSY',3).
grade('Excel','LP',4).
grade('Excel','MTH',4).
grade('Excel','FP',4).
grade('Excel','INF',3).
grade('Excel','ENG',5).
grade('Excel','PSY',4).
grade('Tekstopisov','LP',2).
grade('Tekstopisov','MTH',5).
grade('Tekstopisov','FP',4).
grade('Tekstopisov','INF',3).
grade('Tekstopisov','ENG',5).
grade('Tekstopisov','PSY',3).
grade('Tekstopisova','LP',4).
grade('Tekstopisova','MTH',4).
grade('Tekstopisova','FP',4).
grade('Tekstopisova','INF',3).
grade('Tekstopisova','ENG',5).
grade('Tekstopisova','PSY',2).
grade('Gustobukvennikova','LP',5).
grade('Gustobukvennikova','MTH',2).
grade('Gustobukvennikova','FP',4).
grade('Gustobukvennikova','INF',5).
grade('Gustobukvennikova','ENG',4).
grade('Gustobukvennikova','PSY',3).
grade('Kriptovalutnikov','LP',5).
grade('Kriptovalutnikov','MTH',2).
grade('Kriptovalutnikov','FP',2).
grade('Kriptovalutnikov','INF',3).
grade('Kriptovalutnikov','ENG',4).
grade('Kriptovalutnikov','PSY',2).
grade('Blockchainis','LP',5).
grade('Blockchainis','MTH',2).
grade('Blockchainis','FP',5).
grade('Blockchainis','INF',3).
grade('Blockchainis','ENG',4).
grade('Blockchainis','PSY',5).
grade('Azurin','LP',4).
grade('Azurin','MTH',2).
grade('Azurin','FP',4).
grade('Azurin','INF',3).
grade('Azurin','ENG',5).
grade('Azurin','PSY',2).
grade('Webservisov','LP',3).
grade('Webservisov','MTH',4).
grade('Webservisov','FP',3).
grade('Webservisov','INF',3).
grade('Webservisov','ENG',5).
grade('Webservisov','PSY',2).
grade('Kruglotlichnikov','LP',4).
grade('Kruglotlichnikov','MTH',3).
grade('Kruglotlichnikov','FP',5).
grade('Kruglotlichnikov','INF',5).
grade('Kruglotlichnikov','ENG',3).
grade('Kruglotlichnikov','PSY',5).
